package frontend;
public class FormMenu extends javax.swing.JFrame {

    /**
     * Creates new form FormMenu
     */
    public FormMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuMaster = new javax.swing.JMenu();
        mFormKategori = new javax.swing.JMenuItem();
        mFormAnggota = new javax.swing.JMenuItem();
        mFormBuku = new javax.swing.JMenuItem();
        menuTransaksi = new javax.swing.JMenu();
        tFormPeminjaman = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuMaster.setText("Master");

        mFormKategori.setText("Form Kategori");
        mFormKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFormKategoriActionPerformed(evt);
            }
        });
        menuMaster.add(mFormKategori);

        mFormAnggota.setText("Form Anggota");
        mFormAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFormAnggotaActionPerformed(evt);
            }
        });
        menuMaster.add(mFormAnggota);

        mFormBuku.setText("Form Buku");
        mFormBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFormBukuActionPerformed(evt);
            }
        });
        menuMaster.add(mFormBuku);

        jMenuBar1.add(menuMaster);

        menuTransaksi.setText("Transaksi");

        tFormPeminjaman.setText("Form Peminjaman");
        tFormPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFormPeminjamanActionPerformed(evt);
            }
        });
        menuTransaksi.add(tFormPeminjaman);

        jMenuBar1.add(menuTransaksi);

        jMenu3.setText("Log Out");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mFormKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFormKategoriActionPerformed
        FormKategori frmKategori = new FormKategori();
        frmKategori.setVisible(true);
    }//GEN-LAST:event_mFormKategoriActionPerformed

    private void mFormAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFormAnggotaActionPerformed
        FormAnggota frmAnggota = new FormAnggota();
        frmAnggota.setVisible(true);
    }//GEN-LAST:event_mFormAnggotaActionPerformed

    private void mFormBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFormBukuActionPerformed
        FormBuku frmBuku = new FormBuku();
        frmBuku.setVisible(true);
    }//GEN-LAST:event_mFormBukuActionPerformed

    private void tFormPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFormPeminjamanActionPerformed
        FormPeminjaman frmPeminjaman = new FormPeminjaman();
        frmPeminjaman.setVisible(true);
    }//GEN-LAST:event_tFormPeminjamanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mFormAnggota;
    private javax.swing.JMenuItem mFormBuku;
    private javax.swing.JMenuItem mFormKategori;
    private javax.swing.JMenu menuMaster;
    private javax.swing.JMenu menuTransaksi;
    private javax.swing.JMenuItem tFormPeminjaman;
    // End of variables declaration//GEN-END:variables
}
